apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source

  steps:
    - name: remove
      image: alpine:3
      securityContext:
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: "$(workspaces.source.path)"
      workingDir: "$(workspaces.source.path)"
      script: |
        #!/usr/bin/env sh
        set -eu
        echo "Removing all files from ${WORKSPACE_SOURCE_PATH} ..."
        if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
          rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
          rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
          rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
        fi
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  workspaces:
    - name: source

  params:
    - name: args
      description: Arguments to pass to nose
      type: string
      default: "-v"

  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: "$(workspaces.source.path)"
      securityContext:
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
      script: |
        #!/bin/bash
        set -e
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        nosetests $(params.args)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: openshift-deploy
spec:
  params:
    - name: SCRIPT
      description: |
        oc commands to run during deployment.
        Example: "oc apply -f deployment.yaml"
      type: string

  steps:
    - name: run-oc
      image: quay.io/openshift/origin-cli:latest
      securityContext:
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
      script: |
        #!/usr/bin/env bash
        set -e
        echo "Running OpenShift deployment commands..."
        echo "Executing: $(params.SCRIPT)"
        $(params.SCRIPT)
